# Generated by Django 5.2.8 on 2025-11-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "p_l_unrealized",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("p_l_realized", models.DecimalField(decimal_places=2, max_digits=10)),
                ("win_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("risk_reward_ratio", models.CharField(max_length=10)),
                ("r_multiples", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("entry", models.DecimalField(decimal_places=2, max_digits=10)),
                ("exit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("p_l", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="UpcomingExpiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("strike", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry", models.DateField()),
                ("days_left", models.IntegerField()),
            ],
        ),
    ]
